### PR TITLE
Add dependency on ament_cmake_gtest

### PR DESCRIPTION
**Pull request by sloretz**
https://github.com/ros2/rmw_implementation/pull/106#issuecomment-648489712

@hidmic FYI

### CODE REVIEW

**Comment by sloretz** [comment]
CI (building up to and testing only `test_rmw_implementation`)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11274/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6530/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9231/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11179/)

**Comment by dirk-thomas** [comment]
Shouldn't it be a `test_depend` instead?

**Comment by sloretz** [comment]
> Shouldn't it be a test_depend instead?

I think either works. I picked `buildtool_depend` to match `<buildtool_depend>rmw_implementation_cmake</buildtool_depend>`  which could also be a `test_depend` for the same reason.

**Comment by sloretz** [comment]
> Shouldn't it be a test_depend instead?

Actually, it brings up an interesting case with the `package.xml` when cross-compiling. Does `<test_depend>` mean the dependency is needed on the target machine or the buildtool machine in order to run tests? Maybe there should be a `<buildtool_test_depend>` for dependencies needed only on the buildtool machine to run tests..

**Comment by sloretz** [comment]
> Maybe there should be a <buildtool_test_depend> for dependencies needed only on the buildtool machine to run tests..

Ah nevermind, [REP 149 already covers this](https://ros.org/reps/rep-0149.html#test-depend-multiple):

> When building with testing enabled, the <test_depend> packages are available for configuring and building the tests as well as running them. Generated Debian packages are built without the unit tests or their dependencies.

**Comment by sloretz** [comment]
> Shouldn't it be a test_depend instead?

@dirk-thomas `rmw_implementation_cmake` and `ament_cmake_gtest` made `test_depend` in f7e0563

**Comment by sloretz** [comment]
CI (building and testing `test_rmw_implementation only)
* Linux only as I'll assume a package.xml only change won't affect other platforms [Build Status](https://ci.ros2.org/job/ci_linux/11275/)

**Comment by hidmic** [comment]
Uh, I thought I had added the dependency. Oh well, thanks for the fix @sloretz !!

**Pull request merged**
