### PR TITLE
[Backport Foxy] Added implementation benchmark and test

### PR DESCRIPTION
**Pull request by ahcorde**
Added `rmw_implementation` benchmark and tests

### CODE REVIEW

**Comment by ahcorde** [comment]
Compiling up-to `rmw_implementation` and testing `rmw_implementation`

With `-DAMENT_RUN_PERFORMANCE_TESTS=ON`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12820/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7777/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10534/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12765/)

**Comment by brawner** [comment]
Shouldn't the test arguments just be `--packages-select rmw_implementation`, not `-L performance...`? The only tests that are being run are the benchmark tests.

https://ci.ros2.org/job/ci_linux-aarch64/7777/testReport/

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12834/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7789/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10546/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12777/)

**Comment by ahcorde** [comment]
friendly ping @brawner

**Review by brawner — APPROVED** [review]

**Pull request merged**
