### PR TITLE
consider available rmw implementations at runtime

### PR DESCRIPTION
**Pull request by dirk-thomas**
Alternative to ros2/rmw_implementation#63.

### CODE REVIEW

**Comment by rotu** [comment]
Any reason to keep the build-time dependency on connext/fastrtps/opensplice?

Also, don't forget to remove this now-obsolete check https://github.com/ros2/rmw_implementation/blob/1ca4808d4c4b5cb272038fe2aee0e29f335cdfee/rmw_implementation/CMakeLists.txt#L54-L56

**Comment by dirk-thomas** [comment]
> Any reason to keep the build-time dependency on connext/fastrtps/opensplice?

The comment about `bloom` still applies to them: https://github.com/ros2/rmw_implementation/pull/63#issuecomment-528105897

> Also, don't forget to remove this now-obsolete check

That check is not obsolete. If there is only a single RMW implementation available at build time of `rmw_implementation` then it shouldn't use poco and instead directly link against that RMW implementation (which makes choosing the implementation using an environment variable impossible).

**Comment by rotu** [comment]
1. I don't understand the comment about bloom, so I'm gonna assume you've thought about this and that you're right.
2. If there is 0 or 1 RMW implementations when the underlay is built that doesn't mean there will be a single implementation when rmw_implementation is actually used.
3. This fix seems to work! I'm closing my PRs.

**Comment by dirk-thomas** [comment]
> It seems like maybe it would make sense to have an option like RMW_IMPLEMENTATION_NO_DYNAMIC_LOADING like the existing RMW_IMPLEMENTATION_FORCE_DYNAMIC_LOADING option.

That would be an option to allow forcing dynamic loading even if only one rmw impl is present. Please consider to create a PR for that enhancement.

**Comment by dirk-thomas** [comment]
> It seems like maybe it would make sense to have an option like RMW_IMPLEMENTATION_NO_DYNAMIC_LOADING like the existing RMW_IMPLEMENTATION_FORCE_DYNAMIC_LOADING option.

That would be an option to force static dynamic loading even if more than one rmw impl is present. On the other hand if you really care about that optimization you would probably not have more than one rmw impl. in your workspace in the first place. Anyway please consider to create a PR for that enhancement if you think it is valuable.

**Comment by rotu** [comment]
> Anyway please consider to create a PR for that enhancement if you think it is valuable.

I guess I could, though I still don’t get why the special case is even needed when there is no more than one package.

It really just strikes me as a mistake that there are now two lists of packages that can affect the build: one calculated when rmw_implementation is built and one calculated when downstream consuming packages are built. I don’t see the necessity of *both* `RMW_IMPLEMENTATIONS` and `available_rmw_implementations`, and I can see it causing subtle build bugs down the line.

**Comment by dirk-thomas** [comment]
CI builds (up to `test_communication`) with 2 rmw impls:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8067/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4075/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6573/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7939/)

CI builds (up to `test_communication`) with 1 rmw impl:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8068/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4076/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6574/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7940/)

**Comment by dirk-thomas** [comment]
> It really just strikes me as a mistake that there are now two lists of packages that can affect the build: one calculated when rmw_implementation is built and one calculated when downstream consuming packages are built. I don’t see the necessity of *both* `RMW_IMPLEMENTATIONS` and `available_rmw_implementations`, and I can see it causing subtle build bugs down the line.

I agree that having two different kind of checks is awkward. I just don't see what the alternative should be if the requirement is that the current uses cases should continue to be supported:

* with a single RMW impl. present at build time `rmw_implementation` should directly link against it (for efficiency and simplicity)
* for your use case you want to be able to use an RMW implementation which wasn't available a build time of `rmw_implementation` and select it using the environment variable

Please feel free to propose an alternative approach.

**Comment by rotu** [comment]
Proposed alternate approach in #67

**Comment by dirk-thomas** [comment]
Closing in favor of the merged PR #67.

**Pull request closed without merging**
