### PR TITLE
Run tests for Fast-RTPS based implementations only.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. To speed up RMW layer specs refining and testing.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Why should we *not* test the other RMW impl?

**Comment by hidmic** [comment]
> Why should we not test the other RMW impl?

My understanding is that we don't have the resources to keep updating all RMW implementations to comply with the RMW API specification as it evolves along with the tests. Thus, it's unlikely that without changes those implementations will pass these tests. 

I'm opening this for debate so that, both if we forward with this or we don't, we are all aware of the implications.

**Comment by chapulina** [comment]
> we don't have the resources

I'm looking into this, let's not merge this PR yet :crossed_fingers:

**Comment by dirk-thomas** [comment]
> My understanding is that we don't have the resources to keep updating all RMW implementations to comply with the RMW API specification as it evolves along with the tests. Thus, it's unlikely that without changes those implementations will pass these tests.

In my opinion that would be a very bad direction for the project. This will likely open the door to significant divergence between RMW impl. and leaving a lot of code untested which ultimately leads to reduced quality (just my 2 ct).

**Comment by hidmic** [comment]
It has been decided that we will update Fast-RTPS, CycloneDDS and RTI Connext RMWs accordingly. No need for these restrictions anymore. Closing.

**Pull request closed without merging**
