### PR TITLE
Detect if conflicting default rmw implementations have been specified

### PR DESCRIPTION
**Pull request by dhood**
raised from discussion in https://github.com/ros2/rmw_implementation/issues/10

### CODE REVIEW

**Comment by wjwwood** [comment]
lgtm, I think that will prevent most people from having the wrong expectation when using the `RMW_IMPLEMENATION` CMake/env vars to pick the default.

**Comment by wjwwood** [comment]
@dhood can you run CI over this, at least on Linux just to make sure we don't break master?

**Comment by dhood** [comment]
ok I will

**Comment by dhood** [comment]
I think it's good now http://ci.ros2.org/job/ci_linux/1197/testReport/ (the rclpy tests started failing in build 1191 and I started testing in build 1192)

**Comment by wjwwood** [comment]
@jacquelinekay you might want to have a look at this: http://ci.ros2.org/job/ci_linux/1197/testReport/nose.failure/Failure/runTest/

**Comment by wjwwood** [comment]
lgtm, I tested it locally and it works as expected.

**Pull request merged**
