### PR TITLE
Add gid API test coverage.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. Connected tohttps://github.com/ros2/rmw/pull/274. Depends on https://github.com/ros2/rmw_fastrtps/pull/440, https://github.com/ros2/rmw_cyclonedds/pull/244, and https://github.com/ros2/rmw_connext/pull/461.

### CODE REVIEW

**Comment by hidmic** [comment]
CI up to `test_rmw_implementation`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12383/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7352/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10095/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12296/)

**Review by Lobotuerk — APPROVED** [review]
LGTM

**Review by brawner — APPROVED** [review]

**Comment by hidmic** [comment]
@ros-pull-request-builder retest this please

**Comment by hidmic** [comment]
Had to rebase to solve conflicts. Let's wait for the Rpr check.

**Review by Lobotuerk — APPROVED** [review]
LGTM

**Pull request merged**
