### PR TITLE
Add client/service QoS getters

### PR DESCRIPTION
**Pull request by mauropasse**
Blocked by https://github.com/ros2/rmw_fastrtps/pull/560
https://github.com/ros2/rmw_cyclonedds/pull/343
https://github.com/ros2/rmw_connextdds/pull/67

Signed-off-by: Mauro Passerino <mpasserino@irobot.com>

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
test would be nice to add.

**Comment by mauropasse** [comment]
After some discussion (see https://github.com/ros2/rmw_connextdds/pull/67#discussion_r738447092) I updated all PRs to retrieve independently the QoS for Client request publisher / response subscription and Services request subscription / response publisher.

**Review by ivanpauno — APPROVED** [review]

**Comment by ivanpauno** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15543/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10228/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13212/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15756/)

**Comment by ivanpauno** [comment]
Extra CI run to check linter issues were solved:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15544/)

All the rmw* PRs  look ready to me, I wIll wait for another opinion on the proposed API before merging.

**Comment by ivanpauno** [comment]
Rpr checker will continue failing until I release `rmw`, `rmw_fastrtps`, `rmw_connextdds`, `rmw_cyclonedds`.
I will merge this PR and then do that.

**Comment by Blast545** [comment]
:man_farmer: This PR introduced some linter test regressions into the buildfarm: https://ci.ros2.org/job/nightly_linux_debug/2120/#showFailuresLink.

The linter check job didn't include the package `test_rmw_implementation` which was modified as well.

**Pull request merged**
