### PR TITLE
Symplify rmw interface implementation when multi DDS found

### PR DESCRIPTION
**Pull request by jwang11**
The commit use classic c preprocessor approch to handle variadic parameter. By define
RMW interface implementation and handle ARG values inside RMW_INTERFACE_FN macro,
it obviously reduce code lines and complexity of rmw interface implementation.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for the patch. That indeed significantly decreased the code size.

I applied some minor changes on top in c68550811d43de81b09dd40825052d0f396841ba. I created #29 and triggered some CI builds. It looks like the code doesn't compile on Windows as-is. Could you have a look on how it can be made to work on Windows since we need to support all platforms?

**Comment by jwang11** [comment]
The reason for Windows compile failure lie in the MACRO parse order in a MACRO function and MACRO paramater, like MACRO_FUNC(MACRO_PARAM). In VS, it parse MACRO_FUNC first, but GCC parse MACRO_PARAM firstly. It can be easily resolved #define EXPAND(x) x, which cater both VS and GCC.

**Comment by dirk-thomas** [comment]
Can you commit a patch to this branch? I can then cherry-pick it into the other PR.

**Comment by mikaelarguedas** [comment]
closing this since #29  has been merged.
Thanks @jwang11 for the contribution and for iterating on this!

**Pull request closed without merging**
