### PR TITLE
Remove rmw_connext_cpp.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]

**Review by asorbini — APPROVED** [review]
LGTM as a follow up to #182

**Comment by asorbini** [comment]
Actually, one minor addition: you might want to remove the reference to `rmw_connext_cpp` in `test_rmw_implementation/test/config.hpp` ([I noticed this in my original edits](https://github.com/ros2/rmw_implementation/pull/182/commits/f548cb56525386dba5cc9524162cb017097a6b1d#diff-3c89b5824985eeff893a7b74fb3bfa2125da11761af3a6fac246674415bec99eL27))

**Comment by clalancette** [comment]
> Actually, one minor addition: you might want to remove the reference to `rmw_connext_cpp` in `test_rmw_implementation/test/config.hpp` ([I noticed this in my original edits](https://github.com/ros2/rmw_implementation/pull/182/commits/f548cb56525386dba5cc9524162cb017097a6b1d#diff-3c89b5824985eeff893a7b74fb3bfa2125da11761af3a6fac246674415bec99eL27))

Good call, fixed in 4687ee4

**Comment by clalancette** [comment]
CI for this is at https://github.com/ros2/rmw_connextdds/issues/9#issuecomment-805863900 (the yellow jobs are because of an uncrustify error in rclcpp that has since been fixed).  So I'm going to go ahead and merge this.

**Pull request merged**
