### PR TITLE
add add_executable_for_each_rmw_implementations()

### PR DESCRIPTION
**Pull request by dirk-thomas**
http://ci.ros2.org/job/ros2_batch_ci_linux/226/
http://ci.ros2.org/job/ros2_batch_ci_osx/147/
http://ci.ros2.org/job/ros2_batch_ci_windows/227/

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

Is there a recommended way to use this with a gtest target? Running unit tests against all platforms should be our recommendation, it would be good to make that easy.

**Comment by dirk-thomas** [comment]
The function only creates executables (hence `add_executable_*`). A similar function for tests would be possible but also imply a run dependency on e.g. gtest which I would avoid for something like rmw_implementation.

**Comment by tfoote** [comment]
Yeah, this would be an additional helper function. Can we provide an iterator/helper method instead to feed into a foreach block?

**Comment by dirk-thomas** [comment]
I think it would require quite some changes to make the function produce gtest executables and also register them for tests. It is already possible to iterate all generated targets after calling this function. May be that is a better approach to extend its behavior.

**Comment by tfoote** [comment]
Yeah, 

Maybe just a function to load the various middlewares turning this into a one liner: 

```
  # get the rmw implementations ahead of time
  get_available_rmw_implementations(middleware_implementations)
  foreach(middleware_impl ${middleware_implementations})
    find_package("${middleware_impl}" REQUIRED)
  endforeach()
```

Such that we can recommend doing the below and using the variable: 
```
  # create executables
  foreach(middleware_impl ${middleware_implementations})
    ...
```

**Pull request merged**
