### PR TITLE
Don't find_package(ament_index_cpp ..) if RMW is configured at build-time

### LINKED ISSUE #209: Should ament_index_cpp only be find_package(..)ed when runtime selection is enabled?
## Bug report

**Required Info:**

- Operating System:
  - custom
- Installation type:
  - from source
- Version or commit hash:
  - 31843adc17f28a4af0dc5f160e9e3b4dfb9710ea (`humble` `HEAD`)
- DDS implementation:
  - FastDDS (but not really relevant)
- Client library (if applicable):
  - N/A

This isn't so much an issue as it is a question: #189 added a build dependency on `ament_index_cpp` to `rmw_implementation`:

https://github.com/ros2/rmw_implementation/blob/8c3c133eb070a4f19259f027cc2cea720b28eff0/rmw_implementation/CMakeLists.txt#L15

From the rest of the `CMakeLists.txt`, `ament_index_cpp` only appears to be used when `RMW_IMPLEMENTATION_DISABLE_RUNTIME_SELECTION` is `ON`:

https://github.com/ros2/rmw_implementation/blob/8c3c133eb070a4f19259f027cc2cea720b28eff0/rmw_implementation/CMakeLists.txt#L44-L61

However, because `find_package(ament_index_cpp ..)` appears outside the `if(..) else (..)`, it's always executed, which leads to problems on (build) platforms which do not support C++ nor runtime RMW selection.

Should [line 15](https://github.com/ros2/rmw_implementation/blob/8c3c133eb070a4f19259f027cc2cea720b28eff0/rmw_implementation/CMakeLists.txt#L15) be moved to somewhere around [here](https://github.com/ros2/rmw_implementation/blob/8c3c133eb070a4f19259f027cc2cea720b28eff0/rmw_implementation/CMakeLists.txt#L49-L53), so it is also guarded by `RMW_IMPLEMENTATION_DISABLE_RUNTIME_SELECTION`?

If this would be OK, I could submit a PR introducing this change.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Should fix #209.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I'm currently on Humble, so if this could be backported to `humble`, that would be :+1:

**Comment by gavanderhoorn** [comment]
Not sure what to make of the buildfarm build failing.

**Comment by clalancette** [comment]
> Not sure what to make of the buildfarm build failing.

We need to do some Rolling releases.  I'll do those in a bit.

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
Well, I don't know why the Rpr job is failing; I can't reproduce that locally.  I'm going to run CI on this, and if that is good, merge.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17588/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12128/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18157/)

**Review by clalancette — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Looks like the Jenkins agents get shut down before the build completes?

**Comment by clalancette** [comment]
> Looks like the Jenkins agents get shut down before the build completes?

Sigh, yes.  The aarch64 nodes have been flapping a bit lately.  They automatically restart, but the tracking badge doesn't follow that.  Updated now.

**Comment by clalancette** [comment]
CI looks good here (the yellow jobs just have a CMake warning, and that was fixed elsewhere).  So going ahead and merging this one.

**Comment by gavanderhoorn** [comment]
thanks.

Could this one also be backported to Humble?

**Pull request merged**
