### PR TITLE
Add node graph functions

### PR DESCRIPTION
**Pull request by ross-desmond**
* rmw_get_subscriber_names_and_types_by_node
* rmw_get_publisher_names_and_types_by_node
* rmw_get_service_names_and_types_by_node

Connects to ros2/rcl#333

### CODE REVIEW

**Comment by ross-desmond** [comment]
Connected to [rcl](https://github.com/ros2/rcl/pull/333)

**Comment by thomas-moulard** [comment]
Confirmed tests are passing locally.

**Comment by dirk-thomas** [comment]
The commit list in this PR currently contains several unrelated commits. It would be good to clean this up so that it is obvious what changes are part of this patch.

**Comment by clalancette** [comment]
I just force pushed to cleanup the history.  There is no functional change.

**Pull request merged**
